#!/usr/bin/env bash

#echo "Installing apt dependencies..."
#apt-get install -y python3 python3-pip python3-dev
#
#echo "Installing python3 dependencies..."
#pip3 install -r requirements.txt
#
#echo "Installing Gradescope dependencies..."
#cd GradescopeBase-master
#python3 setup.py install
#cd ../

## uncomment everything above and comment one line bellow to run locally
cd source

python3 main.py

# this line bellow is for creating docker containter with autograder, and two folders are mounted.
## docker run -it --rm -v /Users/khumoyunaminaddinov/PycharmProjects/NewUU/NewUU-CS101-autogradersForLabsHWs:/autograder -v /Users/khumoyunaminaddinov/PycharmProjects/NewUU/NewUU-CS101-autogradersForLabsHWs/results:/autograder/results -e "IS_LOCAL=true" gradescope/autograder-base bash